version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local


    docker run --hostname=8c7b3cd268c0 --env=MYSQL_USER=sail --env=MYSQL_PASSWORD=password --env=MYSQL_ALLOW_EMPTY_PASSWORD=1 --env=MYSQL_ROOT_PASSWORD=password --env=MYSQL_ROOT_HOST=% --env=MYSQL_DATABASE=laravel --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=MYSQL_UNIX_PORT=/var/lib/mysql/mysql.sock --volume=/Users/pfilipiak/workspace/CODITY/products_in_store_api/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh:rw --network=products_in_store_api_sail -p 3306:3306 --label='com.docker.compose.config-hash=0cc1f87a9d40a96565cd3e5545db4633fc7adf1e65bdbd0ccd0811c9c070e9d4' --label='com.docker.compose.container-number=1' --label='com.docker.compose.depends_on=' --label='com.docker.compose.image=sha256:423da140c8c08b22018681200f25555f90bb3ea1c557d455594845c32438707f' --label='com.docker.compose.oneoff=False' --label='com.docker.compose.project=products_in_store_api' --label='com.docker.compose.project.config_files=/Users/pfilipiak/workspace/CODITY/products_in_store_api/docker-compose.yml' --label='com.docker.compose.project.working_dir=/Users/pfilipiak/workspace/CODITY/products_in_store_api' --label='com.docker.compose.service=mysql' --label='com.docker.compose.version=2.15.1' --runtime=runc -d mysql/mysql-server:8.0
